python -m torch.distributed.launch --nproc_per_node=1 \
    --nnodes=1 --master_port=1234 /home/ada/satmae/SatMAE/main_finetune.py \
    --output_dir /home/ada/satmae/other_data/eurosat/evaluation/sentinel \
    --log_dir /home/ada/satmae/other_data/eurosat/evaluation/sentinel \
    --device cuda \
    --batch_size 8 \
    --patch_size 8 \
    --model vit_large_patch16 \
    --model_type group_c \
    --input_size 96 \
    --resume /home/ada/satmae/multispectral/checkpoints/finetune-vit-large-e7.pth  \
    --dist_eval --eval --num_workers 8 --dataset euro_sat \
    --train_path /home/ada/satmae/other_data/eurosat/train_ms.txt \
    --test_path /home/ada/satmae/other_data/eurosat/val_ms.txt \
    --nb_classes 62
