python -m torch.distributed.launch --nproc_per_node=1 \
    --nnodes=1 --master_port=1235 /home/ada/satmae/SatMAE/main_finetune.py \
    --output_dir /home/ada/satmae/multispectral/evaluation/frozen_vit_large \
    --log_dir /home/ada/satmae/multispectral/evaluation/frozen_vit_large \
    --device cuda \
    --batch_size 8 \
    --patch_size 8 \
    --input_size 96 \
    --model vit_large_patch16 \
    --model_type group_c \
    --resume /home/ada/satmae/multispectral/checkpoints/pretrain-vit-large-e199.pth  \
    --dist_eval --eval --num_workers 8 --dataset sentinel \
    --train_path /home/ada/satmae/multispectral/data/fmow-sentinel/train.csv \
    --test_path /home/ada/satmae/multispectral/data/fmow-sentinel/val.csv \
    --nb_classes 62
